
CREATE TABLE MEMBER(
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) UNIQUE NOT NULL,
    MEMBER_PW VARCHAR2(30) NOT NULL,
    MEMBER_NAME VARCHAR2(15) NOT NULL,
    FOOT_SIZE NUMBER
);

CREATE SEQUENCE MEM_SEQ;

INSERT INTO MEMBER VALUES(MEM_SEQ.NEXTVAL, 'user01', 'pass01', 'À¯Àú1', 270);

SELECT * FROM MEMBER;

COMMIT;
