
GRANT CREATE VIEW TO kh;

GRANT SELECT ON kh.EMP_VIEW TO test1;

GRANT CREATE SYNONYM TO kh;
GRANT SELECT ON kh.EMPLOYEE TO test1;
GRANT SELECT ON kh.DEPARTMENT TO test1;

--공개 동의어
CREATE PUBLIC SYNONYM DEPT FOR kh.DEPARTMENT;
DROP PUBLIC SYNONYM DEPT;

--오브젝트 실습
CREATE USER khtest IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO khtest;
GRANT CREATE VIEW TO khtest;
GRANT CREATE SYNONYM TO khtest;
