
CREATE OR REPLACE VIEW EMP_VIEW
AS
SELECT EMP_ID, EMP_NAME, EMAIL, PHONE FROM EMPLOYEE;

CREATE OR REPLACE VIEW EMP_VIEW1
AS 
SELECT EMP_ID, EMAIL FROM EMPLOYEE;

CREATE TABLE EMP_COPY
AS
SELECT EMP_ID, EMP_NAME, EMAIL, PHONE FROM EMPLOYEE;

SELECT * FROM EMPLOYEE;
SELECT * FROM EMP_VIEW;
SELECT * FROM EMP_COPY;

UPDATE EMP_VIEW
SET PHONE = '01099999999'
WHERE EMP_ID = 200;

UPDATE EMPLOYEE
SET PHONE = '01000000000'
WHERE EMP_ID = 200;

ROLLBACK;

CREATE SEQUENCE SEQ_ID
START WITH 100  -- 시작값 100
INCREMENT BY 1  -- 1씩 증가
MAXVALUE 1000   --최대값 1000
NOCYCLE         --1000이후에 증가하지 않고 에러 발생
NOCACHE;        --캐쉬 사용 안함

SELECT SEQ_ID.NEXTVAL, EMPLOYEE.* FROM EMPLOYEE;
SELECT SEQ_ID.CURRVAL FROM DUAL;


CREATE TABLE SEQ_TBL(
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) UNIQUE,
    MEMBER_PW VARCHAR2(30) NOT NULL
);

CREATE SEQUENCE SEQ_TEST
START WITH 1
INCREMENT BY 2
MAXVALUE 3
NOCYCLE
NOCACHE;

INSERT INTO SEQ_TBL VALUES(
    SEQ_TEST.NEXTVAL, 'user01', 'pass01');
INSERT INTO SEQ_TBL VALUES(
    SEQ_TEST.NEXTVAL, 'user02', 'pass02');
INSERT INTO SEQ_TBL VALUES(
    SEQ_TEST.NEXTVAL, 'user03', 'pass03');
INSERT INTO SEQ_TBL VALUES(
    SEQ_TEST.NEXTVAL, 'user04', 'pass04');
    
SELECT * FROM SEQ_TBL;
SELECT MAX(MEMBER_NO) FROM SEQ_TBL;

ALTER SEQUENCE SEQ_TEST
INCREMENT BY 1
MAXVALUE 1000
NOCYCLE
NOCACHE;

DROP SEQUENCE SEQ_TEST;
