
--오브젝스 실습
CREATE TABLE MEMBER(
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_USERID VARCHAR2(20) UNIQUE NOT NULL,
    MEMBER_USERPWD CHAR(20) NOT NULL,
    MEMBER_NICKNAME VARCHAR2(20) UNIQUE NOT NULL,
    MEMBER_GENDER NVARCHAR2(1) NOT NULL CHECK (MEMBER_GENDER IN('남', '여')),
    MEMBER_EMAIL VARCHAR2(30) NOT NULL
);
DROP TABLE MEMBER;
DROP TABLE BOARD;

CREATE SEQUENCE SEQ_MEM
START WITH 1000
INCREMENT BY 1
MAXVALUE 1000000
NOCYCLE
NOCACHE;

CREATE TABLE BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(20) NOT NULL,
    BOARD_CONTENT VARCHAR2(200) NOT NULL,
    BOARD_WRITEDATE DATE NOT NULL,
    BOARD_NICKNAME VARCHAR2(20) NOT NULL,
    FOREIGN KEY(BOARD_NICKNAME) REFERENCES MEMBER(MEMBER_USERID)
);

CREATE SEQUENCE SEQ_BOARD
START WITH 1
INCREMENT BY 1
MAXVALUE 500000
NOCYCLE
NOCACHE;

CREATE VIEW MEM_VIEW
AS
SELECT MEMBER_NO, MEMBER_NICKNAME, MEMBER_EMAIL, BOARD_TITLE
FROM MEMBER
JOIN BOARD ON (MEMBER_USERID = BOARD_NICKNAME);

INSERT INTO MEMBER VALUES(
SEQ_MEM.NEXTVAL, 'user01', 'user01', '유저1', '남', 'user01');
INSERT INTO MEMBER VALUES(
SEQ_MEM.NEXTVAL, 'user02', 'user02', '유저2', '여', 'user02');
INSERT INTO MEMBER VALUES(
SEQ_MEM.NEXTVAL, 'user03', 'user03', '유저3', '남', 'user03');

INSERT INTO BOARD VALUES(
SEQ_BOARD.NEXTVAL, 'board01', 'test01', SYSDATE, 'user01');
INSERT INTO BOARD VALUES(
SEQ_BOARD.NEXTVAL, 'board01', 'test01', SYSDATE, 'user01');
INSERT INTO BOARD VALUES(
SEQ_BOARD.NEXTVAL, 'board01', 'test01', SYSDATE, 'user02');
INSERT INTO BOARD VALUES(
SEQ_BOARD.NEXTVAL, 'board02', 'test03', SYSDATE, 'user03');

SELECT * FROM MEMBER;
SELECT * FROM BOARD;
SELECT * FROM MEM_VIEW;

CREATE SYNONYM M FOR MEMBER;
CREATE SYNONYM B FOR MEMBER;

SELECT * FROM M;
SELECT * FROM B;
