
CREATE TABLE TEST_USER(
    USER_NO NUMBER PRIMARY KEY,
    USER_ID VARCHAR2(20) NOT NULL UNIQUE,
    USER_PW VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    GENDER CHAR(3) CHECK (GENDER IN ('남', '여')),
    PHONE CHAR(13) DEFAULT '010-0000-0000'
);

SELECT * FROM TEST_USER;

INSERT INTO TEST_USER VALUES(
    1, 'user1', 'pass1', 'user1', '남', DEFAULT);
INSERT INTO TEST_USER VALUES(
    2, 'user2', 'pass2', 'user2', '여', DEFAULT);

COMMENT ON COLUMN TEST_USER.USER_NO IS '회원번호';
COMMENT ON COLUMN TEST_USER.USER_ID IS '회원아이디';
COMMENT ON COLUMN TEST_USER.USER_PW IS '회원비밀번호';
COMMENT ON COLUMN TEST_USER.USER_NAME IS '회원이름';
COMMENT ON COLUMN TEST_USER.GENDER IS '성별';
COMMENT ON COLUMN TEST_USER.PHONE IS '전화번호';

CREATE TABLE TEST_BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR2(2000) NOT NULL,
    BOARD_WRITER VARCHAR2(20) NOT NULL REFERENCES TEST_USER(USER_ID),
    WRITE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TEST_BOARD;

INSERT INTO TEST_BOARD VALUES(
    1, 'user1', 'pass1', 'user1', DEFAULT);
INSERT INTO TEST_BOARD VALUES(
    2, 'user1', 'pass1', 'user2', DEFAULT);

COMMENT ON COLUMN TEST_BOARD.BOARD_NO IS '게시물번호';
COMMENT ON COLUMN TEST_BOARD.BOARD_TITLE IS '게시물제목';
COMMENT ON COLUMN TEST_BOARD.BOARD_CONTENT IS '게시물내용';
COMMENT ON COLUMN TEST_BOARD.BOARD_WRITER IS '게시물작성자';
COMMENT ON COLUMN TEST_BOARD.WRITE_DATE IS '게시물작성일';

SELECT * FROM USER_CONS_COLUMNS;
SELECT * FROM USER_CONSTRAINTS;

