
--SUM은 그룹함수이기에 여러줄이 출력되는 DEPT_CODE와 에러가 생긴다.
SELECT DEPT_CODE, SUM(SALARY) FROM EMPLOYEE;
SELECT DEPT_CODE FROM EMPLOYEE;
SELECT SUM(SALARY) FROM EMPLOYEE;

--그룹함수인 SUM과 동시에 사용하기 위해서는 GROUP BY로 그룹함수가 아닌 것을 묶을 필요가 있다.
SELECT DEPT_CODE, SUM(SALARY), FLOOR(AVG(SALARY)) AS "평균", COUNT(*) AS "인원"
FROM EMPLOYEE
GROUP BY DEPT_CODE;

--새로 만들어낸 컬럼도 GROUP BY가 가능하다.
SELECT
    DECODE(SUBSTR(EMP_NO, 8, 1), 1, '남', 2, '여') AS "성별",
    FLOOR(AVG(SALARY)) AS "평균",
    SUM(SALARY) AS "합계",
    COUNT(*) AS "인원수"
FROM EMPLOYEE
GROUP BY DECODE(SUBSTR(EMP_NO, 8, 1), 1, '남', 2, '여');

--부서별 평균 급여
SELECT DEPT_CODE, FLOOR(AVG(SALARY))
FROM EMPLOYEE
GROUP BY DEPT_CODE
HAVING FLOOR(AVG(SALARY)) > 3000000;