
CREATE TABLE MEMBER(
    MEMBER_ID VARCHAR2(20) PRIMARY KEY,
    MEMBER_PW VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    AGE NUMBER NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(11) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL,
    ENROLL_DATE DATE DEFAULT SYSDATE
);
