
CREATE TABLE EXAM_MEMBER(
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) UNIQUE,
    MEMBER_PW VARCHAR2(30) NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    PHONE CHAR(11)
);

COMMENT ON COLUMN EXAM_MEMBER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN EXAM_MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN EXAM_MEMBER.MEMBER_PW IS '비밀번호';
COMMENT ON COLUMN EXAM_MEMBER.MEMBER_NAME IS '이름';
COMMENT ON COLUMN EXAM_MEMBER.PHONE IS '전화번호';

SELECT * FROM EXAM_MEMBER;

CREATE SEQUENCE MEM_SEQ;

CREATE TABLE EXAM_BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR2(2000) NOT NULL,
    BOARD_WRITER VARCHAR2(20) REFERENCES EXAM_MEMBER(MEMBER_ID) ON DELETE SET NULL,
    READ_COUNT NUMBER DEFAULT 0,
    WRITE_DATE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN EXAM_BOARD.BOARD_NO IS '게시물번호';
COMMENT ON COLUMN EXAM_BOARD.BOARD_TITLE IS '제목';
COMMENT ON COLUMN EXAM_BOARD.BOARD_CONTENT IS '내용';
COMMENT ON COLUMN EXAM_BOARD.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN EXAM_BOARD.READ_COUNT IS '조회수';
COMMENT ON COLUMN EXAM_BOARD.WRITE_DATE IS '작성일';

SELECT * FROM EXAM_BOARD;

CREATE SEQUENCE BOARD_SEQ;
