
CREATE TABLE EMP_01(
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(30),
    DEPT_TITLE VARCHAR2(20)
);

INSERT INTO EMP_01 VALUES (1, '박태규', '컴퓨터공학');
INSERT INTO EMP_01 VALUES ('박태규', '컴퓨터공학', 2);  --에러
INSERT INTO EMP_01(EMP_ID, EMP_NAME, DEPT_TITLE) 
VALUES (2, '박태규', '컴퓨터공학');
INSERT INTO EMP_01(EMP_ID, DEPT_TITLE, EMP_NAME) 
VALUES (2, '컴퓨터공학', '박태규');

SELECT * FROM EMP_01;

CREATE TABLE EMP_02(
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(30),
    DEPT_TITLE VARCHAR2(20),
    HIRE_DATE DATE DEFAULT SYSDATE
);

INSERT INTO EMP_02(EMP_ID, DEPT_TITLE, EMP_NAME) 
VALUES (2, '컴퓨터공학', '박태규');
INSERT INTO EMP_02 VALUES(3, '박태규2', '컴퓨터공학', DEFAULT);

SELECT * FROM EMP_02;
