
CREATE TABLE tbl_memo(
    NO NUMBER PRIMARY KEY,
    NAME VARCHAR2(20),
    MSG VARCHAR2(2000),
    WRITEDAY DATE
);

INSERT INTO TBL_MEMO VALUES(101, '한석규', '환영합니다', SYSDATE);
INSERT INTO TBL_MEMO VALUES(102, '유관순', '건강하세요', SYSDATE);
INSERT INTO TBL_MEMO VALUES(103, '이순신', '감사합니다', SYSDATE);

SELECT * FROM TBL_MEMO;

COMMIT;
