
CREATE TABLE NOTICE_COMMENT (
    NOTICE_COMMENT_NO NUMBER PRIMARY KEY,
    NOTICE_COMMENT_LEVEL NUMBER DEFAULT 1,
    NOTICE_COMMENT_WRITER VARCHAR2(20),
    NOTICE_COMMENT_CONTENT VARCHAR2(1000),
    NOTICE_REF NUMBER,
    NOTICE_COMMENT_REF NUMBER,
    NOTICE_COMMENT_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_NOTICE_COMMENT_WRITER FOREIGN KEY(NOTICE_COMMENT_WRITER) 
    REFERENCES MEMBER(MEMBER_ID) ON DELETE SET NULL,
    CONSTRAINT FK_NOTICE_REF FOREIGN KEY(NOTICE_REF)
    REFERENCES NOTICE(NOTICE_NO) ON DELETE CASCADE,
    CONSTRAINT FK_NOTICE_COMMENT_REF FOREIGN KEY(NOTICE_COMMENT_REF)
    REFERENCES NOTICE_COMMENT(NOTICE_COMMENT_NO) ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_NOTICE_COMMENT;

SELECT * FROM NOTICE_COMMENT;
