--계정 생성
CREATE USER test1 IDENTIFIED BY 1234;

--권한 부여
GRANT CONNECT, RESOURCE TO test1;

--권한 해제
REVOKE CONNECT FROM test1;

CREATE USER ddlexam IDENTIFIED BY 1234;

GRANT CONNECT, RESOURCE TO ddlexam;