CREATE TABLE EXPERT_TBL(
    MEMBER_CODE NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) UNIQUE,
    MEMBER_PWD VARCHAR2(20) NOT NULL,
    MEMBER_NAME VARCHAR2(10) NOT NULL,
    MEMBER_ADDR VARCHAR2(50) NOT NULL,
    GENDER CHAR(3) CHECK (GENDER IN('남', '여')),
    PHONE CHAR(13)
);

SELECT * FROM EXPERT_TBL;

INSERT INTO EXPERT_TBL VALUES(
    1, 'user1', '1234', '유저1', '서울', '남', '01012345678');
INSERT INTO EXPERT_TBL VALUES(
    2, 'user2', '1234', '유저1', '서울', '남', '01012345678');
INSERT INTO EXPERT_TBL VALUES(
    3, 'user3', '1234', '유저1', '서울', '여', '01012345678');

CREATE TABLE KHCompany_TBL(
    MEMBER_CODE NUMBER,
    SKILL VARCHAR2(30),
    FOREIGN KEY(MEMBER_CODE) REFERENCEs EXPERT_TBL(MEMBER_CODE)
);

SELECT * FROM KHCOMPANY_TBL;

INSERT INTO KHCOMPANY_TBL VALUES(
    1, '1');
INSERT INTO KHCOMPANY_TBL VALUES(
    2, '1');
