
--LENGTH 함수
SELECT EMP_NAME, LENGTH(EMP_NAME) AS 이름길이, EMAIL, LENGTH(EMAIL) AS 이메일길이 FROM EMPLOYEE;
SELECT EMP_NAME, LENGTHB(EMP_NAME) AS 이름크기, EMAIL, LENGTHB(EMAIL) AS 이메일크기 FROM EMPLOYEE;

--INSTR 함수
SELECT INSTR('Hello World Hi High', 'H', 1, 1) FROM DUAL;
SELECT INSTR('Hello World Hi High', 'H', 1, 2) FROM DUAL;
SELECT INSTR('Hello World Hi High', 'H', 1, 3) FROM DUAL;
SELECT INSTR('Hello World Hi High', 'H', -1, 1) FROM DUAL;
SELECT INSTR('Hello World Hi High', 'H', -1, 2) FROM DUAL;
SELECT INSTR('Hello World Hi High', 'H', 2, 1) FROM DUAL;

--실습
--EMAIL 컬럼 중에서 @문자 위치를 구하시오.
SELECT INSTR(EMAIL, '@', 1, 1) FROM EMPLOYEE;

--LPAD/RPAD
SELECT LPAD(EMAIL, 20, '#') FROM EMPLOYEE;
SELECT LPAD(EMAIL, 10, '#') FROM EMPLOYEE;
SELECT RPAD(EMAIL, 20, '#') FROM EMPLOYEE;
SELECT RPAD(EMAIL, 10, '#') FROM EMPLOYEE;

--LTRIM/RTRIM
SELECT '   KH   ' FROM DUAL;
SELECT LTRIM('   KH   ', ' ')FROM DUAL;
SELECT LTRIM('00012034560', '0') FROM DUAL;
SELECT LTRIM('ACABACCKH', 'ABC') FROM DUAL;
SELECT LTRIM('568543545943216549870KH', '0123456789') FROM DUAL;
SELECT RTRIM('568543545943216549870KH', '0123456789') FROM DUAL;
SELECT LTRIM(RTRIM('568543545943216549870KH12125514256542184251413', '0123456789'), '0123456789') FROM DUAL;

--TRIM
SELECT TRIM('Z' FROM 'ZZZZKZHZZZ') FROM DUAL;
SELECT TRIM(BOTH 'Z' FROM 'ZZZZKZHZZZ') FROM DUAL;
SELECT TRIM(LEADING 'Z' FROM 'ZZZZKZHZZZ') FROM DUAL;
SELECT TRIM(TRAILING 'Z' FROM 'ZZZZKZHZZZ') FROM DUAL;

-- 실습 문제 1
-- Hello KH Java 문자열을 Hello KH 가 출력되게 하여라.
SELECT RTRIM('Hello KH Java', 'Java ') FROM DUAL;
SELECT TRIM(TRAILING 'Java' FROM 'Hello KH Java') FROM DUAL;

-- 실습 문제 2
-- Hello KH Java 문자열을 KH Java 가 출력되게 하여라.
SELECT LTRIM('Hello KH Java', 'Hello ') FROM DUAL;

-- 실습 문제 3 (TRIM으로 해보세요)
-- DEPARTMENT 테이블에서 DEPT_TITLE을 출력하여라
-- 이때, 마지막 부 글자를 빼고 출력되도록 하여라 / ex)회계관리부 -> 회계관리
SELECT * FROM DEPARTMENT;
SELECT TRIM(TRAILING '부' FROM DEPT_TITLE) FROM DEPARTMENT;

-- 실습 문제 4
-- 다음문자열에서 앞뒤 모든 숫자를 제거하세요.
-- '982341678934509hello89798739273402'
SELECT RTRIM(LTRIM('982341678934509hello89798739273402', '0123456789'), '0123456789') FROM DUAL;

--SUBSTR
SELECT 'SHOWMETHEMONEY' FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY', 5, 2) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY', 5) FROM DUAL;
SELECT SUBSTR('SHOWMETHEMONEY', -8, 3) FROM DUAL;

-- 1. 사원명에서 성만 중복없이 사전순으로 출력하세요.
SELECT * FROM EMPLOYEE;
SELECT DISTINCT SUBSTR(EMP_NAME, 1, 1) AS "성" FROM EMPLOYEE ORDER BY 1;

-- 2. EMPLOYEE 테이블에서 남자만
-- 사원번호, 사원명, 주민번호, 연봉을 나타내세요.
-- 주민번호의 뒷 6자리는 *처리하세요.
SELECT EMP_ID, EMP_NAME, RPAD(SUBSTR(EMP_NO, 1, 8), 14, '*') AS 주민번호, SALARY FROM EMPLOYEE WHERE EMP_NO LIKE '%-1%' OR EMP_NO LIKE '%-3%';
--리터럴을 이용해 뒷 6자리에 *처리를 한다.
SELECT EMP_ID, EMP_NAME, SUBSTR(EMP_NO, 1, 8)||'******' AS 주민번호, SALARY FROM EMPLOYEE WHERE EMP_NO LIKE '%-1%' OR EMP_NO LIKE '%-3%';

--LOWER/UPPER/INITCAP
SELECT LOWER('Welcome To My World') FROM DUAL;
SELECT UPPER('Welcome To My World') FROM DUAL;
SELECT INITCAP('welcome to my world') FROM DUAL;

--CONCAT
SELECT CONCAT('ABCD', '가나다라') FROM DUAL;

--REPLACE
SELECT REPLACE('ABCDEFG', 'DEF', '한글') FROM DUAL;

--EMPLOYEE 테이블의 모든 직원의 이름, 주민번호, EMAIL을 출력하시오
--단, 출력시 EMAIL은 kh.or.kr에서 iei.or.kr
--로 변경하여 출력되게 하시오
--ex) sum_di@kh.or.kr -> sum_di@iei.or.kr
SELECT * FROM EMPLOYEE;
SELECT EMP_NAME, EMP_NO, REPLACE(EMAIL, 'kh.or.kr', 'iei.or.kr') AS EMAIL FROM EMPLOYEE;